services:
  - type: web
    name: fc-barcelona-app
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 21
